### ISSUE TITLE
Translations on Frontend

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#106]
Create thesaurus file for all const text/labels/messages, add it to templates and message's text in servers/component using i18n.

[Documentation about feature ](https://angular.io/guide/i18n)

**Comment by PotrusKaterina** [comment]
Translate have to be implemented by ngx-translate technology
3 json vocabulary-files, named "en", "ua" and "ru", have to be created, connected to all components in master and switched by mat-select.
Language, that user select, should be in Local Storage, so users don`t need to translate component again.
