### ISSUE TITLE
Presentational and container components

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#110]
Separate logic and presentation for login, profile and game

[Technical description ](https://blog.angular-university.io/angular-component-design-how-to-avoid-custom-event-bubbling-and-extraneous-properties-in-the-local-component-tree/)

Other articles:

https://blog.angularindepth.com/container-components-with-angular-11e4200f8df

https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why/

http://www.dotnetsurfers.com/blog/2019/01/21/creating-container-and-presentational-components-in-angular/

We should have:
* login.component and login.layout 
* profile.component and profile.layout
* game.component and game.layout
* menu.component
* footer.component
* home.layout which combine menu, footer and router pages

Our structure of client project should be next (root ISDPlatform/Cooper/ClientApp/src/app/):

components/ (**presentational**):
&nbsp;&nbsp;&nbsp;_component-name_/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_component-name_.component.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_component-name_.component.scss
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_component-name_.component.html
&nbsp;&nbsp;&nbsp;index.ts
models/
&nbsp;&nbsp;&nbsp;_model-name_.model.ts
&nbsp;&nbsp;&nbsp;index.ts
services/
&nbsp;&nbsp;&nbsp;_services-name_.service.ts
&nbsp;&nbsp;&nbsp;index.ts
helpers/
&nbsp;&nbsp;&nbsp;_helper-name_.helper.ts
&nbsp;&nbsp;&nbsp;index.ts
layouts/ (**container**)
&nbsp;&nbsp;&nbsp;layout-name/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_layout-name_.layout.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_layout-name_.layout.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_layout-name_.layout.ts
&nbsp;&nbsp;&nbsp;index.ts
pipes/
&nbsp;&nbsp;&nbsp;_pipe-name_.pipe.ts
&nbsp;&nbsp;&nbsp;index.ts

**Comment by AndrePu** [comment]
@PotrusKaterina in this refactoring chain only registration is left)))
