### ISSUE TITLE
Common layout and routings

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#122]
related to #110

Source for this task and example: [see](https://angular.io/guide/router#milestone-5-route-guards)

We should have:

- layout for login page ( /login route)
- platform layout which provides page for authorized user and provides page's layouts as children ( /platform - in example it is path: 'admin')
- platform should have children for each page: /platform/profile/:id, /platform/games, /platform/game/:id and other

Platform layout agregates top panel, footer and current page. 

Platform can have better naming.

In result of task should be:

- ready routing
- login.layout and login-form.component
- platform.layout
- empty top-panel.layout
- empty profile.layout
- empty games.layout
- empty game.layout

**Comment by AndrePu** [comment]
There is still a need to move authguard for routing to a new client.
