### ISSUE TITLE
top menu layout

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#123]
Blocked by #122 , so do it when one will be done

Part of #110 

Provide top-menu.layout for application from old mocks. Where it is possible separete some dump components (might top-menu.component and user-panel.component or other)

**Comment by DmitriyKarpovskiy** [comment]
I propose to create top-menu,layout which will consist of:
1.  navigation.component 
![image](https://user-images.githubusercontent.com/18001679/61279411-bdb6a800-a7be-11e9-9e8d-0cff7a952f87.png)
2. userinfo.component
![image](https://user-images.githubusercontent.com/18001679/61279560-053d3400-a7bf-11e9-9409-9867de6b2130.png)
If it's needed we can add currently logged user's name to this component

**Comment by horba** [comment]
userinfo.component - it's more like global-search.component, but not about some user's data :)

**Comment by DmitriyKarpovskiy** [comment]
After discussion:
Top-menu.layout is consists of elements:
1. Logo
2. navigation.component
3. global-search component
4. avatar.component
5. 'exit' button 

Functional requirements:
1. top-panel.layout should be fixed top 
2. top-panel.layout should be available on each screen after authorization
