### ISSUE TITLE
Profile layout, profile component and related components

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#124]
Blocked by #122 , so do it when one will be done

Part of #110 . It is important to read.

Provide profile-layout for application from old mocks which gets all data to show and profile.component which get all data as input;
Where it is possible separete some dump components (might profile-photo.component, user-info.component, friends-list.component or other)

To refactor IsMy property. Possible but not all variants:

- mode property for profile.component
- different components like friend-profile.component and my-profile.component. Also it can be other layouts with different routes
- others

**Comment by AndrePu** [comment]
#156
