### ISSUE TITLE
Games layout and game's components

### ISSUE THREAD

**Issue by horba** [vanmxpx/ISDPlatform#125]
Blocked by #122 , so do it when one will be done

Part of #110 . It is important to read.

Provide games-layout for application from old mocks which gets all data to show and pass it to related components such as game-list.component, game-card.component and others.

**Comment by PotrusKaterina** [comment]
Create list that show all games and their:
- name
- logo
- genre
- description.

There should be two ways of views: cards and list. Header should be sticky. 
Implement animation and loader.
