### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by justprogrammer2226** [vanmxpx/ISDPlatform#187]
You need to add the "Forget password" button on login from to account and implement the corresponding functionality.

**Functionality:**
It is necessary to implement the password reset functionality for the user if he has forgotten his password. On login form need to add a button "Forgot your password?" which will redirect the user to the password reset page in which he must specify his email and click on the "Reset" button. After clicking on the button, there are 3 options:
1) If the email field is empty, then we notify the user that this field is required
2) If the email field is completed and the email does not exist, then we notify the user that this email does not exist
3) If the email field is completed and the email exists, we notify the user that an email has been sent to his email with a password reset link.

Passing through the password reset link user goes to the page for entering a new password and confirming it.
Next, the user must click on the "Confirm" button and then redirect him to the login form.

**Examples of new view:**
1. On the login form under the password, a link should appear that will redirect the user to the password reset form. <br/><img src="https://user-images.githubusercontent.com/49033815/63074401-d0dfa380-bf35-11e9-8548-461fdaa4e0cb.png" width="350"/>
2. There will be 4 items on the password reset form:
- Title
- Email field
- A field for displaying errors (for example, email is required or email does not exist)
- Button "Reset", when you click on this button, the frontend checks to see if this mail is undefined (if it is undefined, then we can add a specific error that "email is required" and we will not load the server with an unnecessary check for the existence of an email). <br/><img src="https://user-images.githubusercontent.com/49033815/63074732-3f713100-bf37-11e9-8015-acefa40f1a61.png" width="350"/>
3. The password confirmation form is not ready yet, but it should have 5 elements:
- Title
- Password field
- Field for password confirmation
- A field for displaying errors (if the entered passwords do not match)
- The "Confirm" button, when clicked, passwords are validated, the equality of these passwords is checked. And if the passwords are valid and equal, then we redirect the user to the login form. At the same time, the frontend makes a request for a backend in which we update the user’s password by email. If the passwords are not equal, then we display this message in the field for error output.

**Backend:**
1. Add to AuthController 2 method: send reset letter, reset password by token
2. Create a new table in the database to store email and token pairs. For this table create the model and DAO. For UserRepository add method  "ResetPassword(string token, string newPassword)"

**Frontend:**
1. Create a layout with a password reset form and create a password reset component
2. Create service to interact with the desired cooper controller
3. Add link "Forgot your password?" to the login form, whick redirect on layour from the first option
4. Create a layout with a confirm new password form and create a confirm new password component

**New API endpoints:**
- POST api/auth/reset/send
Request:
```
class TargetEmail
{
   public string Email { get; set; }
}
```
Response:
Status code 200 - if reset password email was sent
Status code 400 - if reset password email was not sent

- POST api/auth/reset
Request:
```
class ResetPassword
{
   public string Token { get; set; }
   public string NewPassword { get; set; }
}
```
Response:
Status code 200 - if password was reset
Status code 400 - if password was not reset

**Comment by horba** [comment]
Functionality:
please, describe more detail new view: all fields and buttons there and their purpose and states;

Technical:
1) we don't need separate controller
we can implement it as a method of existing (I hope) AuthController

2) Also we don't need separate service and separate repository
We can create table and DAO layer to work with this table, and our UserRepository can work with this DAO, also business logic is a part of UserService. So we don't new repository and new service

3) please, describe DTOs and models which you are going to use. Also you need provide contract (model of request and response) between server side and front.

**Comment by horba** [comment]
Do we use hash to send password?

**Comment by horba** [comment]
might, add method "ResetPassword(string token, string newPassword) to AuthService instead of UserService. but it will be more obvious in process of development

**Comment by horba** [comment]
Also, in this case is ok to create separate RecoveryController and RecoveryService if you prefer and it will better on your opinion
