### ISSUE TITLE
Repository and DAO

### ISSUE THREAD

**Issue by vanmxpx** [vanmxpx/ISDPlatform#7]
Create layer between db and controllers

**Comment by vlchernet** [comment]
See my branch origin/issue10 please.  It is a draft of model, DAO and contoller for table CHATS. And it seems that this affects this issue # 7.

**Comment by vlchernet** [comment]
See branch origin/issue10 for tracking current state of models, ORM, controllers.

**Comment by AndrePu** [comment]
Controllers for main entities are nominally done
